apiVersion: argoproj.io/vialpha1
kind: Application
metadata:
   name: techtrends-prod
   namespace: argocd
spec:
   destination:
      namespace: default
      server: https://kubernetes.default.svc
   project: default
   source:
      helm:
         valueFiles:
         - values-prod.yaml
      path: helm
      repoURL: https://github.com/madaiart/nd064_course_1/
      targetRevision: HEAD
   syncPolicy: {}