apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: {{ .Values.namespace.name }}
  labels:
    app: techtrends
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory}}
            cpu: {{ .Values.resources.requests.CPU}}
          limits:
            memory: {{ .Values.resources.limits.memory}}
            cpu: {{ .Values.resources.limits.CPU}}

        ports:
        - containerPort: {{ .Values.containerPort }} 
        livenessProbe:
           httpGet:
              path: /healthz
              port:  {{ .Values.containerPort }}
        readinessProbe:
           httpGet:
              path: /healthz
              port: {{ .Values.containerPort }} 