apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: sandbox
spec:
  type: ClusterIP
  selector:
    app: MyApp
  ports:
    - name: techtrends
      protocol: TCP
      port: 4111
      targetPort: 3111